// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_coZSGDGbnX-gGD0ycGzlnOpRWb4n9Dc',
    appId: '1:937797122948:web:089f4981c8709581637bd1',
    messagingSenderId: '937797122948',
    projectId: 'edu-pro-8e259',
    authDomain: 'edu-pro-8e259.firebaseapp.com',
    storageBucket: 'edu-pro-8e259.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqDhcjtnsxb7gX1lV1cSVXZFRJmeNKtw',
    appId: '1:937797122948:android:4226bb2c7e901534637bd1',
    messagingSenderId: '937797122948',
    projectId: 'edu-pro-8e259',
    storageBucket: 'edu-pro-8e259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz8jL7_FMkRdmEX24zYhtXEfJSaPAWEYI',
    appId: '1:937797122948:ios:a944323e52130a04637bd1',
    messagingSenderId: '937797122948',
    projectId: 'edu-pro-8e259',
    storageBucket: 'edu-pro-8e259.firebasestorage.app',
    iosBundleId: 'com.example.eduPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz8jL7_FMkRdmEX24zYhtXEfJSaPAWEYI',
    appId: '1:937797122948:ios:a944323e52130a04637bd1',
    messagingSenderId: '937797122948',
    projectId: 'edu-pro-8e259',
    storageBucket: 'edu-pro-8e259.firebasestorage.app',
    iosBundleId: 'com.example.eduPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_coZSGDGbnX-gGD0ycGzlnOpRWb4n9Dc',
    appId: '1:937797122948:web:57940d8e3d052fa7637bd1',
    messagingSenderId: '937797122948',
    projectId: 'edu-pro-8e259',
    authDomain: 'edu-pro-8e259.firebaseapp.com',
    storageBucket: 'edu-pro-8e259.firebasestorage.app',
  );
}
